name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server_debian:
    runs-on: debian-11
    container: debian:${{ matrix.os }}
    strategy:
      matrix:
        os: [9, 10, 11]

    steps:
    - name: Install i386 deps
      run: |
        apt-get -qq update
        apt-get -y upgrade
        dpkg --add-architecture i386 
        apt-get -y update
        apt-get install lib32z1 -y
        apt-get install build-essential curl make g++-multilib -y
    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-i686-unknown-linux-gnu
        override: true

    - uses: actions/checkout@v2
    - name: Build server plugin
      run: |
        cargo build --package server --release
        strip -s target/release/libserver.so -o stripped.so
    - uses: actions/upload-artifact@v2
      with:
        name: cef-debian-${{ matrix.os }}.so
        path: stripped.so
